services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${ROOT_PATH}frontend:/var/www/app/frontend
      - ${ROOT_PATH}backend:/var/www/app/backend
      - ${SERVER_CONFIG_DIR}/conf.d:/etc/nginx/conf.d
      - ${SERVER_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf
# path to sertificate
      - ${SERVER_CRT_PATH}:/ssl/server.crt:ro
# path to key
      - ${SERVER_KEY_PATH}:/ssl/server.key:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: php
    working_dir: /var/www/app/backend
    volumes:
      - ${ROOT_PATH}backend:/var/www/app/backend
    expose:
      - "9000"
  
  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - laravel-db-data:/var/lib/mysql

volumes:
  laravel-db-data: